insert into PWManager values(0,1,'987654321','email@gmail.com','email','gmail.com');
insert into URLMANAGER values(0,1,'google.com','google');
insert into person values(0,'jduenas12','a1234','jiaying','duenas');
insert into person values(0,'rickyd','b1234','Ricky','duenas');
insert into person values(0,'jhonie','23487','John','Smith');
insert into person values(0,'emalie','35792','Emily')
insert into person (user_login, user_password, first_name, last_name) values ('sladbrooke0', 'bC8DsMIfkj3N', 'Sonia', 'Ladbrooke');
insert into person (user_login, user_password, first_name, last_name) values ('dgibby1', 'wQ9oHas', 'Dina', 'Gibby');
insert into person (user_login, user_password, first_name, last_name) values ('nocannon2', 'TvSCo2tW', 'Nadya', 'O''Cannon');
insert into person (user_login, user_password, first_name, last_name) values ('cjamme3', 'ETunx6d', 'Cyndie', 'Jamme');
insert into person (user_login, user_password, first_name, last_name) values ('dhalsworth4', 'OodiIioOQPsC', 'Danette', 'Halsworth');
insert into person (user_login, user_password, first_name, last_name) values ('cmckinty5', 'yfudCY', 'Caria', 'McKinty');
insert into person (user_login, user_password, first_name, last_name) values ('sdigges6', '2ppwwn', 'Sutton', 'Digges');
insert into person (user_login, user_password, first_name, last_name) values ('bcornfield7', 'OZb4atqQh8', 'Bethanne', 'Cornfield');
insert into person (user_login, user_password, first_name, last_name) values ('wwotherspoon8', 'o0pZr1O', 'Wenonah', 'Wotherspoon');
insert into person (user_login, user_password, first_name, last_name) values ('slarcier9', 'u2SIaeplY', 'Shelbi', 'Larcier');
insert into person (user_login, user_password, first_name, last_name) values ('gdadswella', 'qOwzbZ0jEC6M', 'Gilberto', 'Dadswell');
insert into person (user_login, user_password, first_name, last_name) values ('clongworthb', 'xdKAyksNlk', 'Carline', 'Longworth');
insert into person (user_login, user_password, first_name, last_name) values ('asergisonc', 'p1rxKlu', 'Allison', 'Sergison');
insert into person (user_login, user_password, first_name, last_name) values ('ccallerd', 'NQcCfS', 'Christoforo', 'Caller');
insert into person (user_login, user_password, first_name, last_name) values ('nellicee', 'NFNjpd', 'Noam', 'Ellice');
insert into person (user_login, user_password, first_name, last_name) values ('hflawsf', 'WONQgFUE7k3', 'Honor', 'Flaws');
insert into person (user_login, user_password, first_name, last_name) values ('jclealg', 'd6M3TaQuZ', 'Justen', 'Cleal');
insert into person (user_login, user_password, first_name, last_name) values ('jcochranh', 'VEl962AOm', 'Joshia', 'Cochran');
insert into person (user_login, user_password, first_name, last_name) values ('aconnechiei', 'QeQKUL', 'Amata', 'Connechie');
insert into person (user_login, user_password, first_name, last_name) values ('swyllcockj', 'GO2clBBlxYYo', 'Stormi', 'Wyllcock');
insert into person (user_login, user_password, first_name, last_name) values ('cgrubbek', 'IsWfpq', 'Courtney', 'Grubbe');
insert into person (user_login, user_password, first_name, last_name) values ('mkenchingtonl', '1rYdjq', 'Maddie', 'Kenchington');
insert into person (user_login, user_password, first_name, last_name) values ('bwarmishamm', 'zNeARwXuk', 'Benedicto', 'Warmisham');
insert into person (user_login, user_password, first_name, last_name) values ('chanselmannn', 'MUeBf860', 'Chick', 'Hanselmann');
insert into person (user_login, user_password, first_name, last_name) values ('walmeyo', 'LZTyAtQ9gt5', 'Willard', 'Almey');
insert into person (user_login, user_password, first_name, last_name) values ('hparmleyp', 'kwmqhjhPAylS', 'Hakeem', 'Parmley');
insert into person (user_login, user_password, first_name, last_name) values ('nhainsq', 'emwDaEx9', 'Nadya', 'Hains');
insert into person (user_login, user_password, first_name, last_name) values ('epohlingr', 'HKojvc7ioz', 'Ermanno', 'Pohling');
insert into person (user_login, user_password, first_name, last_name) values ('dgillbes', 'nvAiSSw', 'Danita', 'Gillbe');
insert into person (user_login, user_password, first_name, last_name) values ('lsilvert', 'GApQsrM38', 'Livvie', 'Silver');
insert into person (user_login, user_password, first_name, last_name) values ('apendreu', 'G2foQYwxtOlq', 'Ayn', 'Pendre');
insert into person (user_login, user_password, first_name, last_name) values ('gblazicv', 'SCAZSCBq5Dzb', 'Griff', 'Blazic');
insert into person (user_login, user_password, first_name, last_name) values ('cimortsw', 'vtztSS', 'Carlota', 'Imorts');
insert into person (user_login, user_password, first_name, last_name) values ('awardesworthx', 'caOIyDeMn', 'Ashlie', 'Wardesworth');
insert into person (user_login, user_password, first_name, last_name) values ('bdomotory', 'BnIztC', 'Bar', 'Domotor');
insert into person (user_login, user_password, first_name, last_name) values ('bmullardz', 'yTnLgOHZyKR0', 'Bernette', 'Mullard');
insert into person (user_login, user_password, first_name, last_name) values ('gmolfino10', 'HnnDLR', 'Garry', 'Molfino');
insert into person (user_login, user_password, first_name, last_name) values ('hkarpfen11', 'sAXOh0wrgyj3', 'Hadlee', 'Karpfen');
insert into person (user_login, user_password, first_name, last_name) values ('zragat12', 'BFZegSetj', 'Zuzana', 'Ragat');
insert into person (user_login, user_password, first_name, last_name) values ('cellcock13', 'MAFAwpnz2uD', 'Christie', 'Ellcock');
insert into person (user_login, user_password, first_name, last_name) values ('jrosewall14', 'KcyRllMoEgI', 'Jacobo', 'Rosewall');
insert into person (user_login, user_password, first_name, last_name) values ('jhunsworth15', 'igv9wbYDZl', 'Janot', 'Hunsworth');
insert into person (user_login, user_password, first_name, last_name) values ('rtweed16', 'xTtfdzzhz', 'Rahal', 'Tweed');
insert into person (user_login, user_password, first_name, last_name) values ('qstoggell17', 'ALUtxrsFz9k', 'Quinlan', 'Stoggell');
insert into person (user_login, user_password, first_name, last_name) values ('cmcgifford18', 'Xn5DK6', 'Cyril', 'McGifford');
insert into person (user_login, user_password, first_name, last_name) values ('wkincaid19', '8XLwxtpV4n', 'Waite', 'Kincaid');
insert into person (user_login, user_password, first_name, last_name) values ('inesbit1a', 'C52OPa', 'Isahella', 'Nesbit');
insert into person (user_login, user_password, first_name, last_name) values ('schalliner1b', 'jE6aXYFnF', 'Shantee', 'Challiner');
insert into person (user_login, user_password, first_name, last_name) values ('amckillop1c', 'rlUvHYz', 'Alis', 'McKillop');
insert into person (user_login, user_password, first_name, last_name) values ('tealam1d', 'XW5tSwG3FE3u', 'Tiffanie', 'Ealam');



insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'U2ugPhLlif86', 'dwyson0', 'Monthly', 'http://livejournal.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'uO38wzU5G', 'hslograve1', 'Weekly', 'http://wsj.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'MGJEe4wg7Q', 'phrycek2', 'Once', 'https://ted.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'bBscJ217Dw', 'dpietruszka3', 'Often', 'https://1und1.de');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'A1gOYmeW', 'mhestrop4', 'Daily', 'http://ocn.ne.jp');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'VQVUPRcCL', 'tviegas5', 'Often', 'https://furl.net');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'KYaZvANxWl', 'tleipnik6', 'Monthly', 'https://adobe.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'uqgzjY9rwSsr', 'tbeswell7', 'Often', 'http://mlb.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'2swDJe6', 'djeffcoate8', 'Seldom', 'https://tinyurl.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'QbdKti1eZ8', 'dscollard9', 'Never', 'http://theguardian.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'897whKt', 'mmatzkea', 'Seldom', 'https://so-net.ne.jp');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'XKLgDeGjiJ', 'htitchenerb', 'Once', 'http://weebly.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'JK249WJvQl', 'shatfullc', 'Once', 'https://nifty.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'JdCII4C15eJP', 'aollanderd', 'Seldom', 'https://jimdo.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'sUkSnD2YH', 'vcabelle', 'Often', 'https://sciencedaily.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'5A3u3AfQoQ', 'krandallf', 'Never', 'http://google.com.au');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'M7Sqtkx', 'hjarmaing', 'Weekly', 'https://dion.ne.jp');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'fdBrmElYxf', 'ahartleh', 'Weekly', 'http://pinterest.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'IL0fOLre2', 'edicarlii', 'Seldom', 'https://scribd.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'brxrfT5INL', 'lblacksterj', 'Daily', 'http://free.fr');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'vMfCIa', 'phayerk', 'Monthly', 'https://yelp.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'3eiVUeg', 'arultenl', 'Once', 'https://sina.com.cn');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'HPnu1inv38q', 'dkarchowskim', 'Daily', 'http://google.es');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'YUXsXIdBaWXx', 'zbaldaccon', 'Once', 'https://istockphoto.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'cKMmCooFE6I0', 'jerangyo', 'Never', 'https://ifeng.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'JshXBZmrsEAK', 'hchetwyndp', 'Seldom', 'http://china.com.cn');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'QlaMqJqocPj', 'fgollingq', 'Daily', 'http://cyberchimps.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'XLMu05aPPoR', 'ggiovannazzir', 'Seldom', 'https://printfriendly.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'WthhZe', 'sfrissells', 'Monthly', 'http://webmd.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'hxsuSl3', 'rhinert', 'Never', 'https://dailymail.co.uk');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'PdleBFM', 'ybentkeu', 'Never', 'http://diigo.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'fAnhCIxSUHiI', 'crodgierv', 'Yearly', 'http://opera.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'FmtehdIR', 'ekemw', 'Weekly', 'https://latimes.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'jzi25KyklFMM', 'fploughwrightx', 'Seldom', 'https://ameblo.jp');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'lup03LOJ', 'rpembertony', 'Once', 'https://etsy.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'RWGADC6', 'fantonognoliz', 'Weekly', 'http://aol.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'n8td5MWg', 'sglenton10', 'Daily', 'https://lycos.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'6TSRNNf', 'rjoubert11', 'Yearly', 'https://aboutads.info');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'M3Mup6', 'acrowdy12', 'Weekly', 'https://newyorker.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'cusgsi6ax', 'smarien13', 'Often', 'https://ning.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'0zZucyovCT', 'cbonnick14', 'Never', 'https://adobe.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'hTxXkhy', 'ghardypiggin15', 'Yearly', 'http://meetup.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'sXTjaA43xwK', 'gkondratyuk16', 'Weekly', 'http://pcworld.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'2ozx2zXlUO7', 'bcrinkley17', 'Monthly', 'http://storify.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'oKf3vOM', 'aphilbrick18', 'Seldom', 'https://163.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'ReCy8Icx', 'caisthorpe19', 'Seldom', 'https://google.co.jp');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'GP3BFytTx8gG', 'ldyers1a', 'Daily', 'https://cnet.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'WL0iV56JCl', 'acancott1b', 'Yearly', 'http://walmart.com');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'lcwRnB', 'akoppelmann1c', 'Daily', 'https://g.co');
insert into pwmanager ( personID,passwrd, accnt, descprtion, URL) values (1,'PbTO7aLCE0t', 'srape1d', 'Seldom', 'http://hibu.com');


insert into urlmanager (personID, url, descprtion) values (1, 'https://tumblr.com', 'Yearly');
insert into urlmanager (personID, url, descprtion) values (1, 'http://fotki.com', 'Never');
insert into urlmanager (personID, url, descprtion) values (1, 'https://odnoklassniki.ru', 'Never');
insert into urlmanager (personID, url, descprtion) values (1, 'https://rambler.ru', 'Weekly');
insert into urlmanager (personID, url, descprtion) values (1, 'http://bravesites.com', 'Daily');
insert into urlmanager (personID, url, descprtion) values (1, 'https://netvibes.com', 'Daily');
insert into urlmanager (personID, url, descprtion) values (1, 'https://usnews.com', 'Yearly');
insert into urlmanager (personID, url, descprtion) values (1, 'http://flickr.com', 'Seldom');
insert into urlmanager (personID, url, descprtion) values (1, 'http://phoca.cz', 'Once');
insert into urlmanager (personID, url, descprtion) values (1, 'http://wikipedia.org', 'Often');
insert into urlmanager (personID, url, descprtion) values (1, 'https://latimes.com', 'Monthly');
insert into urlmanager (personID, url, descprtion) values (1, 'https://telegraph.co.uk', 'Once');
insert into urlmanager (personID, url, descprtion) values (1, 'http://paypal.com', 'Yearly');
insert into urlmanager (personID, url, descprtion) values (1, 'http://mlb.com', 'Often');
insert into urlmanager (personID, url, descprtion) values (1, 'http://mayoclinic.com', 'Daily');
insert into urlmanager (personID, url, descprtion) values (1, 'https://amazon.de', 'Seldom');
insert into urlmanager (personID, url, descprtion) values (1, 'http://msn.com', 'Once');
insert into urlmanager (personID, url, descprtion) values (1, 'http://webmd.com', 'Daily');
insert into urlmanager (personID, url, descprtion) values (1, 'https://plala.or.jp', 'Seldom');
insert into urlmanager (personID, url, descprtion) values (1, 'https://uol.com.br', 'Daily');
insert into urlmanager (personID, url, descprtion) values (1, 'https://irs.gov', 'Daily');
insert into urlmanager (personID, url, descprtion) values (1, 'https://hatena.ne.jp', 'Monthly');
insert into urlmanager (personID, url, descprtion) values (1, 'https://webmd.com', 'Monthly');
insert into urlmanager (personID, url, descprtion) values (1, 'http://ihg.com', 'Yearly');
insert into urlmanager (personID, url, descprtion) values (1, 'https://quantcast.com', 'Often');
insert into urlmanager (personID, url, descprtion) values (1, 'http://vistaprint.com', 'Yearly');
insert into urlmanager (personID, url, descprtion) values (1, 'https://github.io', 'Monthly');
insert into urlmanager (personID, url, descprtion) values (1, 'http://census.gov', 'Once');
insert into urlmanager (personID, url, descprtion) values (1, 'http://qq.com', 'Never');
insert into urlmanager (personID, url, descprtion) values (1, 'http://liveinternet.ru', 'Yearly');
insert into urlmanager (personID, url, descprtion) values (1, 'http://wiley.com', 'Yearly');
insert into urlmanager (personID, url, descprtion) values (1, 'http://newyorker.com', 'Seldom');
insert into urlmanager (personID, url, descprtion) values (1, 'https://guardian.co.uk', 'Monthly');
insert into urlmanager (personID, url, descprtion) values (1, 'https://spiegel.de', 'Often');
insert into urlmanager (personID, url, descprtion) values (1, 'http://abc.net.au', 'Weekly');
insert into urlmanager (personID, url, descprtion) values (1, 'https://discuz.net', 'Seldom');
insert into urlmanager (personID, url, descprtion) values (1,'https://ning.com', 'Often');
insert into urlmanager (personID, url, descprtion) values (1, 'http://xing.com', 'Yearly');
insert into urlmanager (personID, url, descprtion) values (1, 'http://istockphoto.com', 'Once');
insert into urlmanager (personID, url, descprtion) values (1, 'http://constantcontact.com', 'Once');
insert into urlmanager (personID, url, descprtion) values (1, 'http://joomla.org', 'Weekly');
insert into urlmanager (personID, url, descprtion) values (1, 'http://usnews.com', 'Often');
insert into urlmanager (personID, url, descprtion) values (1, 'https://huffingtonpost.com', 'Seldom');
insert into urlmanager (personID, url, descprtion) values (1, 'http://wiley.com', 'Monthly');
insert into urlmanager (personID, url, descprtion) values (1, 'http://lulu.com', 'Monthly');
insert into urlmanager (personID, url, descprtion) values (1, 'http://wufoo.com', 'Seldom');
insert into urlmanager (personID, url, descprtion) values (1, 'https://home.pl', 'Seldom');
insert into urlmanager (personID, url, descprtion) values (1, 'http://fda.gov', 'Seldom');
insert into urlmanager (personID, url, descprtion) values (1, 'http://gnu.org', 'Often');
insert into urlmanager (personID, url, descprtion) values (1, 'http://edublogs.org', 'Monthly');